"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from decouple import config
from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR,'.env'))
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    r'C:\Users\Administrator\Desktop\ecomjam\espd2501ecommerce\static',
]
STATIC_ROOT = r'C:\Users\Administrator\Desktop\ecomjam\espd2501ecommerce\staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = r'C:\Users\Administrator\Desktop\ecomjam\espd2501ecommerce\media'
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2@&d5sl_e10@@ry2f&rd*j!*!#wx%+8)lvei1ro+r405(h3c$s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'product',
    'account',
    'cart',
    'order',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.sqlite3',
   #     'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

DATABASES={
  'default':{
    'ENGINE':'django.db.backends.postgresql',
    'NAME':os.environ.get('DB_NAME'),
    'USER':os.environ.get('DB_USER'),
    'PASSWORD':os.environ.get('DB_PASSWORD'),
    'HOST':os.environ.get('DB_HOST'),
    'PORT':os.environ.get('DB_PORT'),
    'OPTIONS':{
      'sslmode':'require',
    },

},
}





AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title": "Jama Kapor Admin",
    "site_header": "Jama Kapor Dashboard",
    "site_brand": "Jama Kapor",
    "welcome_sign": "Welcome to Jama Kapor",
    "copyright": "MyCompany © 2025",
    #"topmenu_links": [
     #   {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
      #  {"model": "auth.User"},
       # {"app": "books"},
        #{"name": "Support", "url": "https://example.com/support", "new_window": True},
    #],
    #"usermenu_links": [
     #   {"name": "Support", "url": "https://example.com/support", "new_window": True},
      #  {"model": "auth.user"},
    #],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "books": "fas fa-book",
    },
    "show_sidebar": True,
    "navigation_expanded": True,
    "search_model": "auth.User",
    "order_with_respect_to": ["auth", "books"],
    "custom_css": "css/custom_admin.css",
    "custom_js": "js/custom_admin.js",
    "site_logo": "images/jamakapor.png",  # Path relative to static files

    # Optional: logo classes to control size/appearance
    "site_logo_classes": "img-circle",  # adds rounded style, for example
}

JJAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark navbar-dark",           # dark navbar
    "sidebar": "sidebar-dark sidebar-dark-primary",# dark sidebar with primary color
    "sidebar_fixed": True,                          # fix sidebar for easy navigation
    "navbar_fixed": True,                           # fix navbar at top
    "accent": "accent-primary",                     # primary accent color for highlights
}